[package]
name = "fastack"
version = "0.1.0"
edition = "2024"
authors = ["Abhinav"]

[dependencies]

[dev-dependencies]
criterion = "0.7.0"

[target.'cfg(loom)'.dependencies]
loom = {version = "0.7", features = ["checkpoint"]}

[[bench]]
name = "benchmark"
harness = false


